import { useQuery } from '@tanstack/react-query'
import { Link } from 'react-router-dom'
import { api } from '../lib/api'
import type { Activity, Task } from '../types'
import { Badge, ErrorState, formatDate, formatNumber, Loading, MetricCard, PageHeader } from '../components/ui'

interface Dashboard { activities: number; pending: number; verified: number; corrections: number; rejected: number; learners: number; leads: number; admissions: number; active_partners: number; recent_activities: Activity[]; upcoming_tasks: Task[]; notifications: {id:string;title:string;message:string;is_read:boolean;created_at:string}[]; challenge: { targets: Record<string,number>; achieved: Record<string,number> } }
export default function AlcDashboard() {
  const { data, isLoading, error } = useQuery({ queryKey: ['alc-dashboard'], queryFn: () => api.get<Dashboard>('/portal/dashboard') })
  if (isLoading) return <Loading label="Preparing your dashboard"/>; if (error || !data) return <ErrorState error={error}/>
  return <><PageHeader title="ALC Dashboard" description="Your centre’s verified growth and current work." actions={<Link to="/portal/activities/new" className="btn-primary">Record activity</Link>}/>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Activities submitted" value={data.activities}/><MetricCard label="Pending verification" value={data.pending}/><MetricCard label="Verified activities" value={data.verified}/><MetricCard label="Correction required" value={data.corrections}/><MetricCard label="Verified learners" value={formatNumber(data.learners)} hint="Verified activities only"/><MetricCard label="Verified leads" value={formatNumber(data.leads)} hint="Verified activities only"/><MetricCard label="Verified admissions" value={formatNumber(data.admissions)} hint="Verified activities only"/><MetricCard label="Active partnerships" value={data.active_partners}/></div>
    <section className="mt-6 panel p-5"><div className="mb-4"><h2 className="font-bold text-navy">30-Day Collaboration Challenge</h2><p className="text-sm text-slate-500">Official progress uses verified activities and active partners.</p></div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{Object.keys(data.challenge.targets).map((key) => { const achieved = data.challenge.achieved[key] ?? 0; const target = data.challenge.targets[key] ?? 0; const pct = Math.min(100, target ? achieved / target * 100 : 0); return <div key={key}><div className="flex justify-between text-sm"><span className="capitalize font-medium">{key}</span><span>{achieved} / {target}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-teal" style={{ width: `${pct}%` }}/></div></div> })}</div></section>
    <div className="mt-6 grid gap-6 xl:grid-cols-[1.4fr_.8fr]"><section><div className="mb-3 flex items-center justify-between"><h2 className="font-bold text-navy">Recent activities</h2><Link className="text-sm font-semibold text-teal" to="/portal/activities">View all</Link></div><div className="table-wrap"><table><thead><tr><th>Activity</th><th>Date</th><th>Status</th></tr></thead><tbody>{data.recent_activities.map((a) => <tr key={a.id}><td><Link to={`/portal/activities/${a.id}`} className="font-semibold text-navy hover:text-teal">{a.activity_number}</Link><p className="text-xs text-slate-500">{a.activity_type}</p></td><td>{formatDate(a.activity_date)}</td><td><Badge status={a.status}/></td></tr>)}</tbody></table></div></section><section><h2 className="mb-3 font-bold text-navy">Upcoming tasks</h2><div className="panel divide-y">{data.upcoming_tasks.length ? data.upcoming_tasks.map((t) => <div key={t.id} className="p-4"><p className="text-sm font-semibold">{t.title}</p><p className="mt-1 text-xs text-slate-500">Due {formatDate(t.due_date)}</p></div>) : <p className="p-5 text-sm text-slate-500">No open tasks.</p>}</div></section></div>
    <section className="mt-6"><h2 className="mb-3 font-bold text-navy">Recent verification results</h2><div className="panel divide-y">{data.notifications.length?data.notifications.map(n=><div key={n.id} className={`p-4 ${n.is_read?'':'bg-teal/5'}`}><div className="flex items-center justify-between gap-3"><b className="text-sm">{n.title}</b><span className="text-xs text-slate-500">{formatDate(n.created_at)}</span></div><p className="mt-1 text-sm text-slate-600">{n.message}</p></div>):<p className="p-5 text-sm text-slate-500">No review results yet.</p>}</div></section>
  </>
}
