import { useQuery, useQueryClient } from '@tanstack/react-query'
import { Link, useNavigate } from 'react-router-dom'
import { AlertTriangle, ChevronRight } from 'lucide-react'
import { api } from '../lib/api'
import type { Activity, Task } from '../types'
import { Badge, ErrorState, formatDate, formatNumber, Loading, MetricCard, PageHeader } from '../components/ui'

interface Notice { id:string; title:string; message:string; is_read:boolean; created_at:string; entity_type?:string|null; entity_id?:string|null }
interface Dashboard { activities: number; pending: number; verified: number; corrections: number; rejected: number; learners: number; leads: number; admissions: number; active_partners: number; recent_activities: Activity[]; upcoming_tasks: Task[]; notifications: Notice[]; challenge: { targets: Record<string,number>; achieved: Record<string,number> } }
const CORRECTIONS_URL = '/portal/activities?status=CORRECTION_REQUIRED'

export default function AlcDashboard() {
  const navigate = useNavigate(); const client = useQueryClient()
  const { data, isLoading, error } = useQuery({ queryKey: ['alc-dashboard'], queryFn: () => api.get<Dashboard>('/portal/dashboard') })
  async function openNotice(n: Notice) {
    if (!n.is_read) { try { await api.post(`/portal/notifications/${n.id}/read`); client.invalidateQueries({ queryKey: ['alc-dashboard'] }) } catch { /* marking read is best-effort */ } }
    if (n.entity_type === 'activity' && n.entity_id) navigate(`/portal/activities/${n.entity_id}`)
  }
  if (isLoading) return <Loading label="Preparing your dashboard"/>; if (error || !data) return <ErrorState error={error}/>
  return <><PageHeader title="ALC Dashboard" description="Your centre’s verified growth and current work." actions={<Link to="/portal/activities/new" className="btn-primary">Record activity</Link>}/>
    {data.corrections > 0 && <Link to={CORRECTIONS_URL} className="mb-5 flex items-center gap-3 rounded-lg border border-amber-300 bg-amber-50 p-4 hover:bg-amber-100"><AlertTriangle className="h-5 w-5 shrink-0 text-amber-700"/><div className="flex-1"><p className="font-semibold text-amber-900">{data.corrections} {data.corrections === 1 ? 'activity needs' : 'activities need'} correction</p><p className="text-sm text-amber-800">Your reviewer asked for changes. Open {data.corrections === 1 ? 'it' : 'them'}, fix the details, and resubmit.</p></div><span className="inline-flex items-center gap-1 text-sm font-semibold text-amber-900">Review now<ChevronRight className="h-4 w-4"/></span></Link>}
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Activities submitted" value={data.activities}/><MetricCard label="Pending verification" value={data.pending}/><MetricCard label="Verified activities" value={data.verified} hint={`${data.rejected} rejected`}/><Link to={CORRECTIONS_URL} className="block rounded-lg transition hover:ring-2 hover:ring-amber-300" title="Show activities that need correction"><MetricCard label="Correction required" value={data.corrections} hint={data.corrections ? 'Click to fix and resubmit' : 'Nothing to fix'}/></Link><MetricCard label="Verified learners" value={formatNumber(data.learners)} hint="Verified activities only"/><MetricCard label="Verified leads" value={formatNumber(data.leads)} hint="Verified activities only"/><MetricCard label="Verified admissions" value={formatNumber(data.admissions)} hint="Verified activities only"/><MetricCard label="Active partnerships" value={data.active_partners}/></div>
    <section className="mt-6 panel p-5"><div className="mb-4"><h2 className="font-bold text-navy">30-Day Collaboration Challenge</h2><p className="text-sm text-slate-500">Official progress uses verified activities and active partners.</p></div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{Object.keys(data.challenge.targets).map((key) => { const achieved = data.challenge.achieved[key] ?? 0; const target = data.challenge.targets[key] ?? 0; const pct = Math.min(100, target ? achieved / target * 100 : 0); return <div key={key}><div className="flex justify-between text-sm"><span className="capitalize font-medium">{key}</span><span>{achieved} / {target}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-teal" style={{ width: `${pct}%` }}/></div></div> })}</div></section>
    <div className="mt-6 grid gap-6 xl:grid-cols-[1.4fr_.8fr]"><section><div className="mb-3 flex items-center justify-between"><h2 className="font-bold text-navy">Recent activities</h2><Link className="text-sm font-semibold text-teal" to="/portal/activities">View all</Link></div>{data.recent_activities.length ? <div className="table-wrap"><table><thead><tr><th>Activity</th><th>Date</th><th>Status</th></tr></thead><tbody>{data.recent_activities.map((a) => <tr key={a.id}><td><Link to={`/portal/activities/${a.id}`} className="font-semibold text-navy hover:text-teal">{a.activity_number}</Link><p className="text-xs text-slate-500">{a.activity_type}</p></td><td>{formatDate(a.activity_date)}</td><td><Badge status={a.status}/></td></tr>)}</tbody></table></div> : <div className="panel p-5 text-sm text-slate-500">No activities yet. <Link to="/portal/activities/new" className="font-semibold text-teal">Record your first activity</Link>.</div>}</section><section><h2 className="mb-3 font-bold text-navy">Upcoming tasks</h2><div className="panel divide-y">{data.upcoming_tasks.length ? data.upcoming_tasks.map((t) => <div key={t.id} className="p-4"><p className="text-sm font-semibold">{t.title}</p><p className="mt-1 text-xs text-slate-500">Due {formatDate(t.due_date)}</p></div>) : <p className="p-5 text-sm text-slate-500">No open tasks.</p>}</div></section></div>
    <section className="mt-6"><h2 className="mb-3 font-bold text-navy">Recent verification results</h2><div className="panel divide-y">{data.notifications.length?data.notifications.map(n=>{ const linked = n.entity_type === 'activity' && !!n.entity_id; return <button type="button" key={n.id} onClick={()=>openNotice(n)} disabled={!linked && n.is_read} className={`block w-full p-4 text-left ${n.is_read?'':'bg-teal/5'} ${linked?'hover:bg-slate-50':''}`}><div className="flex items-center justify-between gap-3"><b className="text-sm">{!n.is_read && <span className="mr-2 inline-block h-2 w-2 rounded-full bg-teal align-middle" aria-label="Unread"/>}{n.title}</b><span className="flex items-center gap-1 text-xs text-slate-500">{formatDate(n.created_at)}{linked && <ChevronRight className="h-3.5 w-3.5"/>}</span></div><p className="mt-1 text-sm text-slate-600">{n.message}</p></button> }):<p className="p-5 text-sm text-slate-500">No review results yet.</p>}</div></section>
  </>
}