import { useState } from 'react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { api } from '../lib/api'
import type { Partner } from '../types'
import { Badge, Empty, ErrorState, Loading, PageHeader } from '../components/ui'

const blank={partner_name:'',partner_type:'',ecosystem:'',contact_person:'',phone:'',email:'',location:'',status:'ACTIVE',notes:''}
export default function Partners(){const client=useQueryClient();const [form,setForm]=useState(blank);const [open,setOpen]=useState(false);const [error,setError]=useState('');const query=useQuery({queryKey:['partners'],queryFn:()=>api.get<Partner[]>('/alc/partners')});async function save(e:React.FormEvent){e.preventDefault();setError('');try{await api.post('/alc/partners',form);setForm(blank);setOpen(false);client.invalidateQueries({queryKey:['partners']})}catch(e){setError(e instanceof Error?e.message:'Unable to save partner')}}return <><PageHeader title="Partners" description="Maintain your centre’s local collaboration network." actions={<button className="btn-primary" onClick={()=>setOpen(!open)}>{open?'Close':'Add partner'}</button>}/>{open&&<form onSubmit={save} className="panel mb-5 grid gap-4 p-5 md:grid-cols-2"><div><label>Partner name</label><input className="mt-1" required value={form.partner_name} onChange={e=>setForm({...form,partner_name:e.target.value})}/></div><div><label>Partner type</label><input className="mt-1" required value={form.partner_type} onChange={e=>setForm({...form,partner_type:e.target.value})}/></div><div><label>Ecosystem</label><select className="mt-1" required value={form.ecosystem} onChange={e=>setForm({...form,ecosystem:e.target.value})}><option value="">Select</option>{['School','College','Government','Business','Industry','NGO','Community','Training institution','Youth organization','Other'].map(x=><option key={x}>{x}</option>)}</select></div><div><label>Contact person</label><input className="mt-1" value={form.contact_person} onChange={e=>setForm({...form,contact_person:e.target.value})}/></div><div><label>Phone</label><input className="mt-1" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></div><div><label>Email</label><input className="mt-1" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></div><div className="md:col-span-2"><label>Location</label><input className="mt-1" value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></div>{error&&<p className="text-sm text-red-700 md:col-span-2">{error}</p>}<div className="md:col-span-2"><button className="btn-primary">Save partner</button></div></form>}{query.isLoading?<Loading/>:query.error?<ErrorState error={query.error}/>:!query.data?.length?<Empty title="No partners yet" message="Add institutions and organizations you work with."/>:<div className="table-wrap"><table><thead><tr><th>Partner</th><th>Type</th><th>Ecosystem</th><th>Contact</th><th>Location</th><th>Status</th></tr></thead><tbody>{query.data.map(p=><tr key={p.id}><td className="font-semibold">{p.partner_name}</td><td>{p.partner_type}</td><td>{p.ecosystem}</td><td>{p.contact_person??'—'}<p className="text-xs text-slate-500">{p.phone??p.email}</p></td><td>{p.location??'—'}</td><td><Badge status={p.status}/></td></tr>)}</tbody></table></div>}</>}

